config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'foodboxes#index'
  resources :foodboxes
  resources :users, only: :show
end

app/models/foodbox.rb
class Foodbox < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :foodboxes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/foodboxes_controller.rb
class FoodboxesController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_index, except: :index
  def index
    @foodboxes = Foodbox.all
  end

  def show
    @foodboxes = Foodbox.all
  end

  def new
    @foodbox = Foodbox.new
  end

  def create
    Foodbox.create(foodbox_params)
  end

  def edit
    @foodbox = Foodbox.find(params[:id])
  end

  def update
    foodbox=Foodbox.find(params[:id])
    foodbox.update(foodbox_params) if current_user.id == foodbox.user_id
  end

  def destroy
    foodbox=Foodbox.find(params[:id])
    foodbox.destroy if current_user.id == foodbox.user_id
  end

  private
  def foodbox_params
    params.require(:foodbox).permit(:photo, :restaurant, :comment).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  before_action :move_to_index, except: :index
  def index
    @foods = Foodbox.all
  end

  def show
    
  end

  def new
    
  end

  def create
    Foodbox.create(foodbox_params)
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    
  end

  private
  def foodbox_params
    params.permit(:photo, :restaurant, :comment)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname=current_user.nickname
    @foodboxes=Foodbox.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodboxes_helper.rb
module FoodboxesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foodboxes/create.html.erb
<div class="container">
  <div class="row text-center">
      <div class="col-sm-6 col-sm-offset-3">
        <h2 style="color:#0fad00">Success</h2>
        <img src="http://osmhotels.com//assets/check-true.jpg">
        <br><br>
        <%= link_to 'HOME', root_path, method: :get %>
      </div>
  </div>
</div>

app/views/foodboxes/destroy.html.erb
<div class="container">
  <div class="row text-center">
      <div class="col-sm-6 col-sm-offset-3">
        <h2 style="color:#0fad00">Delete Successful</h2>
        <img src="http://osmhotels.com//assets/check-true.jpg">
        <br><br>
        <%= link_to 'HOME', root_path, method: :get %>
      </div>
  </div>
</div>

app/views/foodboxes/edit.html.erb
<%= form_for (@foodbox) do |f| %>
<div class="container">

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
      <form role="form">
      <h2>Edit</h2>
      <hr class="colorgraph">

      <div class="form-group">
        <%= f.text_field :restaurant, class:"form-control input-lg", tabindex: "3", placeholder: "Restaurant" %>
      </div>
      <div class="form-group">
         <%= f.text_field :photo, class: "form-control input-lg", placeholder: "Image URL", tabindex: "4"%>
      </div>
      <div class="form-group">
         <%= f.text_field :comment, class: "form-control input-lg", placeholder: "Comment", tabindex: "5"%>
      </div>

      <hr class="colorgraph">
      <div class="row">
 <!--        <div class="col-xs-6 col-md-6">
        <input type="button" value="Register" class="btn btn-primary btn-block btn-lg" tabindex="6"></div> -->
        <div class="col-xs-6 col-md-6">
<!--         <a href="#" class="btn btn-success btn-block btn-lg">sent</a> -->
        <%= f.submit "SENT", class: "btn btn-success btn-block btn-lg" %>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
      </div>
      <div class="modal-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>

<% end %>

app/views/foodboxes/index.html.erb
<div class="container-fluid">
  <% @foodboxes.each_slice(4) do |foodboxes| %>
    <div class="row fh5co-post-entry">

    <% foodboxes.each do |foodbox| %>
      <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
        <figure>
          <a><%= image_tag foodbox.photo, :class => "img-responsive" %></a>
        </figure>
        <span class="fh5co-meta"><a><%= foodbox.comment %></a></span>
        <h2 class="fh5co-article-title"><a><%= foodbox.restaurant %></a></h2>
        <span class="fh5co-meta fh5co-date"><%= foodbox.user.nickname %>
        <% if user_signed_in? && foodbox.user_id == current_user.id %>
          <%= link_to 'edit', edit_foodbox_path(foodbox.id), method: :get %>

          <%= link_to 'delete', foodbox_path(foodbox.id), method: :delete %>
        <% end %>
      </span>
      <span class="fh5co-meta fh5co-date"><%= foodbox.created_at.strftime("%Y.%m.%d") %></span>
      </article>
    <% end %>
  </div>
  <% end %>
  <div class="clearfix visible-lg-block visible-md-block visible-sm-block visible-xs-block">
  </div>

  <div class="clearfix visible-xs-block">
  </div>
</div>

app/views/foodboxes/new.html.erb
<%= form_for (@foodbox) do |f| %>
<div class="container">

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
      <form role="form">
      <h2>Post</h2>
      <hr class="colorgraph">

      <div class="form-group">
        <%= f.text_field :restaurant, class:"form-control input-lg", tabindex: "3", placeholder: "Restaurant" %>
      </div>
      <div class="form-group">
         <%= f.text_field :photo, class: "form-control input-lg", placeholder: "Image URL", tabindex: "4"%>
      </div>
      <div class="form-group">
         <%= f.text_field :comment, class: "form-control input-lg", placeholder: "Comment", tabindex: "5"%>
      </div>

      <hr class="colorgraph">
      <div class="row">
 <!--        <div class="col-xs-6 col-md-6">
        <input type="button" value="Register" class="btn btn-primary btn-block btn-lg" tabindex="6"></div> -->
        <div class="col-xs-6 col-md-6">
<!--         <a href="#" class="btn btn-success btn-block btn-lg">sent</a> -->
        <%= f.submit "SENT", class: "btn btn-success btn-block btn-lg" %>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
      </div>
      <div class="modal-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>

<% end %>

app/views/foodboxes/update.html.erb
<div class="container">
  <div class="row text-center">
      <div class="col-sm-6 col-sm-offset-3">
        <h2 style="color:#0fad00">Update Successful</h2>
        <img src="http://osmhotels.com//assets/check-true.jpg">
        <br><br>
        <%= link_to 'HOME', root_path, method: :get %>
      </div>
  </div>
</div>

app/views/foods/index.html.erb
<% @foods.each do |foodbox| %>
  <h2><%= foodbox.restaurant %></h2>
  <%= image_tag foodbox.photo, :size => "300x300" %>
  <p><%= foodbox.user.nickname %></p>
  <p><%= foodbox.comment %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
<!--   <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <title>Eatingram</title>
<!--   <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
  <meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
  <meta name="author" content="FREEHTML5.CO" />

  <meta property="og:title" content=""/>
  <meta property="og:image" content=""/>
  <meta property="og:url" content=""/>
  <meta property="og:site_name" content=""/>
  <meta property="og:description" content=""/>
  <meta name="twitter:title" content="" />
  <meta name="twitter:image" content="" />
  <meta name="twitter:url" content="" />
  <meta name="twitter:card" content="" /> -->

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <link rel="shortcut icon" href="favicon.ico">
  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic|Roboto:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "animate" %>
  <%= stylesheet_link_tag "icomoon" %>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>



  <!-- Modernizr JS -->
  <script src="js/modernizr-2.6.2.min.js"></script>
  <!-- FOR IE9 below -->

  <!-- <script src="js/respond.min.js"></script> -->

  </head>
  <body>
  <div id="fh5co-offcanvas">
    <a href="#" class="fh5co-close-offcanvas js-fh5co-close-offcanvas"><span><i class="icon-cross3"></i> <span>Close</span></span></a>
    <div class="fh5co-bio">
    <% if user_signed_in? %>
      <h2><%= current_user.nickname %></h2>
    <% else %>
      <h2>Welcome!</h2>
    <% end %>
    </div>

    <div class="fh5co-menu">
      <div class="fh5co-box">
        <h3 class="heading">Menu</h3>
        <ul>
          <% if user_signed_in? %>
            <li><a><%= link_to "sign out", destroy_user_session_path, method: :delete %></a></li>
            <li><a><%= link_to "post", new_foodbox_path, method: :get %></a></li>
            <li><a><%= link_to "mypage", user_path(current_user.id), method: :get %></a></li>
          <% else %>
            <li><a><%= link_to "sign up", new_user_registration_path, method: :get %></a></li>
            <li><a><%= link_to "sign in", new_user_session_path, method: :get %></a></li>
          <% end %>
        </ul>
      </div>
      <div class="fh5co-box">
      </div>
    </div>
  </div>
  <!-- END #fh5co-offcanvas -->
  <header id="fh5co-header">
    
    <div class="container-fluid">

      <div class="row">
        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
        <div class="col-lg-12 col-md-12 text-center">
          <h1 id="fh5co-logo"><%= link_to 'Eatingram', root_path, method: :get %></h1>
        </div>

      </div>
    
    </div>

  </header>
<!--   <header id="fh5co-header">
    <div class="container-fluid">

      <div class="row">

        <div class="col-lg-12 col-md-12 text-center">
          <h1 id="fh5co-logo"><a href="/">Eatingram </a></h1>
        </div>

      </div>
    </div>



  <% if user_signed_in? %>
    <%= current_user.nickname %>
      <%= link_to "sign out", destroy_user_session_path, method: :delete %>
      <%= link_to "post", new_foodbox_path, method: :get %>
      <%= link_to "mypage", user_path(current_user.id), method: :get %>

  
  <% else %>
        <%= link_to "sign up", new_user_registration_path, method: :get %>
        <%= link_to "sign in", new_user_session_path, method: :get %>
  <% end %>

  </header> -->

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
  <div class="container-fluid">
      <h3>
        <%= @nickname %>'s page
      </h3>
    <div class="row fh5co-post-entry">
      <% @foodboxes.each do |foodbox| %>
      <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
        <figure>
          <a><%= image_tag foodbox.photo, :class => "img-responsive", :size => '230x175' %></a>
        </figure>
        <span class="fh5co-meta"><a><%= foodbox.comment %></a></span>
        <h2 class="fh5co-article-title"><a><%= foodbox.restaurant %></a></h2>
      </article>
    <% end %>

      <div class="clearfix visible-lg-block visible-md-block visible-sm-block visible-xs-block"></div>

      <div class="clearfix visible-xs-block"></div>
    </div>
  </div>